# Generated by Django 4.2.14 on 2025-05-26 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
