# Generated by Django 4.2.14 on 2025-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="자기소개"
            ),
        ),
    ]
