# Generated by Django 4.2.14 on 2025-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_article_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[("이벤트", "공지사항"), ("tip", "자유게시판")],
                default="tip",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[("normal", "일반"), ("notice", "공지"), ("event", "이벤트")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
