# Generated by Django 4.2.14 on 2025-05-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_article_category_article_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="type",
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("notice", "공지사항"),
                    ("event", "이벤트"),
                    ("tip", "자유게시판"),
                ],
                default="tip",
                max_length=20,
            ),
        ),
    ]
