# Generated by Django 4.2.14 on 2025-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_remove_article_type_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
    ]
