# Generated by Django 4.2.14 on 2025-05-25 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0006_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
