# Generated by Django 4.2.14 on 2025-05-25 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0003_remove_favorite_user_delete_metalprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositproduct",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_deposits", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="savingproduct",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_savings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
